# Generated by Django 2.2.1 on 2019-05-29 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortnr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortlink',
            name='url',
            field=models.URLField(db_index=True),
        ),
    ]
