# Generated by Django 2.2.1 on 2019-05-29 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortnr', '0003_userlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlink',
            name='user_id',
            field=models.CharField(db_index=True, max_length=32),
        ),
        migrations.AddConstraint(
            model_name='userlink',
            constraint=models.UniqueConstraint(fields=('user_id', 'link'), name='unique_link_per_user'),
        ),
    ]
